# Generated by Django 3.1.7 on 2021-03-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=250)),
                ('dosen', models.CharField(max_length=250)),
                ('sks', models.IntegerField()),
                ('deskripsi', models.TextField()),
                ('semester', models.CharField(max_length=6)),
                ('tahun_ajar', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=125)),
                ('deadline', models.DateField()),
                ('mataKuliah', models.ForeignKey(blank=True, default='none', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.matakuliah')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
